# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('andrewID', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
